#
# APCu configuration
#
# http://php.net/manual/fr/apc.configuration.php
#
apc_enable: "1"
apc_shm_size: "256M"
apc_num_files_hint: 0
apc_user_entries_hint: 0
apc_user_ttl: 360
apc_ttl: 360
apc_gc_ttl: 0
# Set to 1 only if your writes are atomic (rsync ok, cp/tar/vim nok)
apc_file_update_protection: 0


#
# php.ini
#
php_ini:
  - group_name: 'PHP'
    conf:
      - key: 'asp_tags'
        value: 'Off'
      - key: 'max_file_uploads'
        value: '20'
      - key: 'display_startup_errors'
        value: 'Off'
      - key: 'precision'
        value: '14'
      - key: 'implicit_flush'
        value: 'Off'
      - key: 'register_argc_argv'
        value: 'Off'
      - key: 'html_errors'
        value: 'On'
      - key: 'short_open_tag'
        value: 'Off'
      - key: 'zend.enable_gc'
        value: 'On'
      - key: 'post_max_size'
        value: '8M'
      - key: 'default_socket_timeout'
        value: '60'
      - key: 'expose_php'
        value: 'On'
      - key: 'disable_classes'
        value: ''
      - key: 'max_input_time'
        value: '60'
      - key: 'ignore_repeated_errors'
        value: 'Off'
      - key: 'serialize_precision'
        value: '17'
      - key: 'log_errors'
        value: 'On'
      - key: 'ignore_repeated_source'
        value: 'Off'
      - key: 'auto_globals_jit'
        value: 'On'
      - key: 'file_uploads'
        value: 'On'
      - key: 'auto_append_file'
        value: ''
      - key: 'zlib.output_compression'
        value: 'Off'
      - key: 'engine'
        value: 'On'
      - key: 'output_buffering'
        value: '4096'
      - key: 'doc_root'
        value: ''
      - key: 'track_errors'
        value: 'Off'
      - key: 'display_errors'
        value: 'Off'
      - key: 'log_errors_max_len'
        value: '1024'
      - key: 'unserialize_callback_func'
        value: ''
      - key: 'allow_url_include'
        value: 'Off'
      - key: 'user_dir'
        value: ''
      - key: 'auto_prepend_file'
        value: ''
      - key: 'report_memleaks'
        value: 'On'
      - key: 'upload_max_filesize'
        value: '2M'
      - key: 'memory_limit'
        value: '128M'
      - key: 'max_execution_time'
        value: '30'
      - key: 'allow_url_fopen'
        value: 'On'
      - key: 'enable_dl'
        value: 'Off'
  - group_name: 'CLI Server'
    conf:
      - key: 'cli_server.color'
        value: 'On'
  - group_name: 'Pdo_mysql'
    conf:
      - key: 'pdo_mysql.cache_size'
        value: '2000'
      - key: 'pdo_mysql.default_socket'
        value: ''
  - group_name: 'mail function'
    conf:
      - key: 'smtp_port'
        value: '25'
      - key: 'mail.add_x_header'
        value: 'On'
      - key: 'SMTP'
        value: 'localhost'
  - group_name: 'SQL'
    conf:
      - key: 'sql.safe_mode'
        value: 'Off'
  - group_name: 'ODBC'
    conf:
      - key: 'odbc.check_persistent'
        value: 'On'
      - key: 'odbc.defaultlrl'
        value: '4096'
      - key: 'odbc.defaultbinmode'
        value: '1'
      - key: 'odbc.allow_persistent'
        value: 'On'
  - group_name: 'Interbase'
    conf:
      - key: 'ibase.allow_persistent'
        value: '1'
  - group_name: 'MySQL'
    conf:
      - key: 'mysql.default_port'
        value: ''
      - key: 'mysql.default_host'
        value: ''
      - key: 'mysql.connect_timeout'
        value: '60'
      - key: 'mysql.default_password'
        value: ''
      - key: 'mysql.allow_persistent'
        value: 'On'
      - key: 'mysql.trace_mode'
        value: 'Off'
      - key: 'mysql.allow_local_infile'
        value: 'On'
      - key: 'mysql.default_socket'
        value: ''
      - key: 'mysql.cache_size'
        value: '2000'
      - key: 'mysql.default_user'
        value: ''
  - group_name: 'MySQLi'
    conf:
      - key: 'mysqli.default_socket'
        value: ''
      - key: 'mysqli.default_port'
        value: '3306'
      - key: 'mysqli.allow_persistent'
        value: 'On'
      - key: 'mysqli.cache_size'
        value: '2000'
      - key: 'mysqli.default_host'
        value: ''
      - key: 'mysqli.default_user'
        value: ''
      - key: 'mysqli.default_pw'
        value: ''
      - key: 'mysqli.reconnect'
        value: 'Off'
  - group_name: 'mysqlnd'
    conf:
      - key: 'mysqlnd.collect_statistics'
        value: 'On'
      - key: 'mysqlnd.collect_memory_statistics'
        value: 'Off'
  - group_name: 'PostgreSQL'
    conf:
      - key: 'pgsql.auto_reset_persistent'
        value: 'Off'
      - key: 'sybct.min_client_severity'
        value: '10'
      - key: 'pgsql.ignore_notice'
        value: '0'
      - key: 'sybct.allow_persistent'
        value: 'On'
      - key: 'pgsql.allow_persistent'
        value: 'On'
      - key: 'pgsql.log_notice'
        value: '0'
      - key: 'sybct.min_server_severity'
        value: '10'
  - group_name: 'bcmath'
    conf:
      - key: 'bcmath.scale'
        value: '0'
  - group_name: 'Session'
    conf:
      - key: 'session.gc_divisor'
        value: '1000'
      - key: 'session.gc_probability'
        value: '0'
      - key: 'session.auto_start'
        value: '0'
      - key: 'session.cache_limiter'
        value: 'nocache'
      - key: 'session.name'
        value: 'PHPSESSID'
      - key: 'session.referer_check'
        value: ''
      - key: 'session.bug_compat_42'
        value: 'Off'
      - key: 'session.use_strict_mode'
        value: '0'
      - key: 'session.cache_expire'
        value: '180'
      - key: 'session.serialize_handler'
        value: 'php'
      - key: 'session.gc_maxlifetime'
        value: '1440'
      - key: 'session.cookie_httponly'
        value: ''
      - key: 'session.use_cookies'
        value: '1'
      - key: 'session.hash_bits_per_character'
        value: '5'
      - key: 'session.cookie_lifetime'
        value: '0'
      - key: 'session.save_handler'
        value: 'files'
      - key: 'session.bug_compat_warn'
        value: 'Off'
      - key: 'session.hash_function'
        value: '0'
      - key: 'session.use_only_cookies'
        value: '1'
      - key: 'session.cookie_domain'
        value: ''
      - key: 'session.use_trans_sid'
        value: '0'
  - group_name: 'MSSQL'
    conf:
      - key: 'mssql.secure_connection'
        value: 'Off'
      - key: 'mssql.allow_persistent'
        value: 'On'
      - key: 'mssql.compatibility_mode'
        value: 'Off'
      - key: 'mssql.min_error_severity'
        value: '10'
      - key: 'mssql.min_message_severity'
        value: '10'
  - group_name: 'Tidy'
    conf:
      - key: 'tidy.clean_output'
        value: 'Off'
  - group_name: 'soap'
    conf:
      - key: 'soap.wsdl_cache_enabled'
        value: '1'
      - key: 'soap.wsdl_cache_ttl'
        value: '86400'
      - key: 'soap.wsdl_cache_limit'
        value: '5'

#
# PHP-FPM pools
#
php_fpm_socket: 'unix'
php_fpm_unix_sockets:
  - pool_name: 'default'
    mode: '0660'
    user: 'www-data'
    group: 'www-data'
    file: '/var/run/php5-fpm.sock'
    pm_max_children: 250
    pm_start_servers: 10
    pm_min_spare_servers: 10
    pm_max_spare_servers: 20

# not tested yet
php_fpm_tcp_sockets:
  - pool_name: 'default'
    user: 'www-data'
    group: '{{ ansible_default_ipv4.address }}'
    ip: '1.1.1.1'
    port: 9000
    pm_max_children: 250
    pm_start_servers: 10
    pm_min_spare_servers: 10
    pm_max_spare_servers: 20

